@echo off
echo Cleaning up port 3001...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3001') do taskkill /f /pid %%a >nul 2>&1
echo Building Frontend...
call npm run build
echo Starting Server...
start "" "http://localhost:3001"
node server/index.js
